/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExcursionsIndexRouteImport } from './routes/excursions.index'
import { Route as ExcursionsSlugRouteImport } from './routes/excursions.$slug'
import { Route as GuidePriveIndexRouteImport } from './routes/guide-prive.index'
import { Route as GuidePriveDemiJourneeRouteImport } from './routes/guide-prive.demi-journee'
import { Route as GuidePriveJourneeCompleteRouteImport } from './routes/guide-prive.journee-complete'
import { Route as TransfertsAeroportIndexRouteImport } from './routes/transferts-aeroport.index'
import { Route as TransfertsAeroportArriveeRouteImport } from './routes/transferts-aeroport.arrivee'
import { Route as TransfertsAeroportDepartRouteImport } from './routes/transferts-aeroport.depart'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionsIndexRoute = ExcursionsIndexRouteImport.update({
  id: '/excursions/',
  path: '/excursions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionsSlugRoute = ExcursionsSlugRouteImport.update({
  id: '/excursions/$slug',
  path: '/excursions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidePriveIndexRoute = GuidePriveIndexRouteImport.update({
  id: '/guide-prive/',
  path: '/guide-prive/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidePriveDemiJourneeRoute = GuidePriveDemiJourneeRouteImport.update({
  id: '/guide-prive/demi-journee',
  path: '/guide-prive/demi-journee',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidePriveJourneeCompleteRoute =
  GuidePriveJourneeCompleteRouteImport.update({
    id: '/guide-prive/journee-complete',
    path: '/guide-prive/journee-complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransfertsAeroportIndexRoute = TransfertsAeroportIndexRouteImport.update({
  id: '/transferts-aeroport/',
  path: '/transferts-aeroport/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfertsAeroportArriveeRoute =
  TransfertsAeroportArriveeRouteImport.update({
    id: '/transferts-aeroport/arrivee',
    path: '/transferts-aeroport/arrivee',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransfertsAeroportDepartRoute =
  TransfertsAeroportDepartRouteImport.update({
    id: '/transferts-aeroport/depart',
    path: '/transferts-aeroport/depart',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/excursions/$slug': typeof ExcursionsSlugRoute
  '/guide-prive/demi-journee': typeof GuidePriveDemiJourneeRoute
  '/guide-prive/journee-complete': typeof GuidePriveJourneeCompleteRoute
  '/transferts-aeroport/arrivee': typeof TransfertsAeroportArriveeRoute
  '/transferts-aeroport/depart': typeof TransfertsAeroportDepartRoute
  '/excursions/': typeof ExcursionsIndexRoute
  '/guide-prive/': typeof GuidePriveIndexRoute
  '/transferts-aeroport/': typeof TransfertsAeroportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/excursions/$slug': typeof ExcursionsSlugRoute
  '/guide-prive/demi-journee': typeof GuidePriveDemiJourneeRoute
  '/guide-prive/journee-complete': typeof GuidePriveJourneeCompleteRoute
  '/transferts-aeroport/arrivee': typeof TransfertsAeroportArriveeRoute
  '/transferts-aeroport/depart': typeof TransfertsAeroportDepartRoute
  '/excursions': typeof ExcursionsIndexRoute
  '/guide-prive': typeof GuidePriveIndexRoute
  '/transferts-aeroport': typeof TransfertsAeroportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/excursions/$slug': typeof ExcursionsSlugRoute
  '/guide-prive/demi-journee': typeof GuidePriveDemiJourneeRoute
  '/guide-prive/journee-complete': typeof GuidePriveJourneeCompleteRoute
  '/transferts-aeroport/arrivee': typeof TransfertsAeroportArriveeRoute
  '/transferts-aeroport/depart': typeof TransfertsAeroportDepartRoute
  '/excursions/': typeof ExcursionsIndexRoute
  '/guide-prive/': typeof GuidePriveIndexRoute
  '/transferts-aeroport/': typeof TransfertsAeroportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/contact'
    | '/faq'
    | '/excursions/$slug'
    | '/guide-prive/demi-journee'
    | '/guide-prive/journee-complete'
    | '/transferts-aeroport/arrivee'
    | '/transferts-aeroport/depart'
    | '/excursions/'
    | '/guide-prive/'
    | '/transferts-aeroport/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/contact'
    | '/faq'
    | '/excursions/$slug'
    | '/guide-prive/demi-journee'
    | '/guide-prive/journee-complete'
    | '/transferts-aeroport/arrivee'
    | '/transferts-aeroport/depart'
    | '/excursions'
    | '/guide-prive'
    | '/transferts-aeroport'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/activites'
    | '/contact'
    | '/faq'
    | '/excursions/$slug'
    | '/guide-prive/demi-journee'
    | '/guide-prive/journee-complete'
    | '/transferts-aeroport/arrivee'
    | '/transferts-aeroport/depart'
    | '/excursions/'
    | '/guide-prive/'
    | '/transferts-aeroport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActivitesRoute: typeof ActivitesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ExcursionsSlugRoute: typeof ExcursionsSlugRoute
  GuidePriveDemiJourneeRoute: typeof GuidePriveDemiJourneeRoute
  GuidePriveJourneeCompleteRoute: typeof GuidePriveJourneeCompleteRoute
  TransfertsAeroportArriveeRoute: typeof TransfertsAeroportArriveeRoute
  TransfertsAeroportDepartRoute: typeof TransfertsAeroportDepartRoute
  ExcursionsIndexRoute: typeof ExcursionsIndexRoute
  GuidePriveIndexRoute: typeof GuidePriveIndexRoute
  TransfertsAeroportIndexRoute: typeof TransfertsAeroportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursions/': {
      id: '/excursions/'
      path: '/excursions'
      fullPath: '/excursions/'
      preLoaderRoute: typeof ExcursionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursions/$slug': {
      id: '/excursions/$slug'
      path: '/excursions/$slug'
      fullPath: '/excursions/$slug'
      preLoaderRoute: typeof ExcursionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-prive/': {
      id: '/guide-prive/'
      path: '/guide-prive'
      fullPath: '/guide-prive/'
      preLoaderRoute: typeof GuidePriveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-prive/demi-journee': {
      id: '/guide-prive/demi-journee'
      path: '/guide-prive/demi-journee'
      fullPath: '/guide-prive/demi-journee'
      preLoaderRoute: typeof GuidePriveDemiJourneeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-prive/journee-complete': {
      id: '/guide-prive/journee-complete'
      path: '/guide-prive/journee-complete'
      fullPath: '/guide-prive/journee-complete'
      preLoaderRoute: typeof GuidePriveJourneeCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferts-aeroport/': {
      id: '/transferts-aeroport/'
      path: '/transferts-aeroport'
      fullPath: '/transferts-aeroport/'
      preLoaderRoute: typeof TransfertsAeroportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferts-aeroport/arrivee': {
      id: '/transferts-aeroport/arrivee'
      path: '/transferts-aeroport/arrivee'
      fullPath: '/transferts-aeroport/arrivee'
      preLoaderRoute: typeof TransfertsAeroportArriveeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferts-aeroport/depart': {
      id: '/transferts-aeroport/depart'
      path: '/transferts-aeroport/depart'
      fullPath: '/transferts-aeroport/depart'
      preLoaderRoute: typeof TransfertsAeroportDepartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActivitesRoute: ActivitesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ExcursionsSlugRoute: ExcursionsSlugRoute,
  GuidePriveDemiJourneeRoute: GuidePriveDemiJourneeRoute,
  GuidePriveJourneeCompleteRoute: GuidePriveJourneeCompleteRoute,
  TransfertsAeroportArriveeRoute: TransfertsAeroportArriveeRoute,
  TransfertsAeroportDepartRoute: TransfertsAeroportDepartRoute,
  ExcursionsIndexRoute: ExcursionsIndexRoute,
  GuidePriveIndexRoute: GuidePriveIndexRoute,
  TransfertsAeroportIndexRoute: TransfertsAeroportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
